In [2]:
from sklearn.neighbors import KernelDensity
import numpy as np

In [74]:
X = np.array([1,2,3,8,9,10]).reshape(-1, 1)
X

array([[ 1],
       [ 2],
       [ 3],
       [ 8],
       [ 9],
       [10]])

In [70]:
kde = KernelDensity(kernel='tophat', bandwidth=.5).fit(X) #this is uniform kernel

In [71]:
np.exp(kde.score_samples([[3]]))

array([0.16666667])

In [75]:
kde = KernelDensity(kernel='tophat', bandwidth=1.5).fit(X) #this is uniform kernel

In [77]:
np.exp(kde.score_samples([[3]]))

array([0.11111111])